// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/MessageProto.proto

package com.regent.rpush.common.protocol;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.MessageProtocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 fromTo = 2;</code>
     * @return Whether the fromTo field is set.
     */
    boolean hasFromTo();
    /**
     * <code>required int64 fromTo = 2;</code>
     * @return The fromTo.
     */
    long getFromTo();

    /**
     * <code>required int64 sendTo = 4;</code>
     * @return Whether the sendTo field is set.
     */
    boolean hasSendTo();
    /**
     * <code>required int64 sendTo = 4;</code>
     * @return The sendTo.
     */
    long getSendTo();

    /**
     * <code>required string content = 1;</code>
     * @return Whether the content field is set.
     */
    boolean hasContent();
    /**
     * <code>required string content = 1;</code>
     * @return The content.
     */
    String getContent();
    /**
     * <code>required string content = 1;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>required int32 type = 3;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>required int32 type = 3;</code>
     * @return The type.
     */
    int getType();
  }
  /**
   * Protobuf type {@code protocol.MessageProtocol}
   */
  public static final class MessageProtocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.MessageProtocol)
      MessageProtocolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageProtocol.newBuilder() to construct.
    private MessageProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageProtocol() {
      content_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageProtocol();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              content_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              fromTo_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000008;
              type_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000002;
              sendTo_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageProto.internal_static_protocol_MessageProtocol_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageProto.internal_static_protocol_MessageProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageProtocol.class, Builder.class);
    }

    private int bitField0_;
    public static final int FROMTO_FIELD_NUMBER = 2;
    private long fromTo_;
    /**
     * <code>required int64 fromTo = 2;</code>
     * @return Whether the fromTo field is set.
     */
    @Override
    public boolean hasFromTo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 fromTo = 2;</code>
     * @return The fromTo.
     */
    @Override
    public long getFromTo() {
      return fromTo_;
    }

    public static final int SENDTO_FIELD_NUMBER = 4;
    private long sendTo_;
    /**
     * <code>required int64 sendTo = 4;</code>
     * @return Whether the sendTo field is set.
     */
    @Override
    public boolean hasSendTo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int64 sendTo = 4;</code>
     * @return The sendTo.
     */
    @Override
    public long getSendTo() {
      return sendTo_;
    }

    public static final int CONTENT_FIELD_NUMBER = 1;
    private volatile Object content_;
    /**
     * <code>required string content = 1;</code>
     * @return Whether the content field is set.
     */
    @Override
    public boolean hasContent() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string content = 1;</code>
     * @return The content.
     */
    @Override
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string content = 1;</code>
     * @return The bytes for content.
     */
    @Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>required int32 type = 3;</code>
     * @return Whether the type field is set.
     */
    @Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required int32 type = 3;</code>
     * @return The type.
     */
    @Override
    public int getType() {
      return type_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFromTo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSendTo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, content_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(2, fromTo_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(3, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(4, sendTo_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, content_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, fromTo_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, sendTo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessageProtocol)) {
        return super.equals(obj);
      }
      MessageProtocol other = (MessageProtocol) obj;

      if (hasFromTo() != other.hasFromTo()) return false;
      if (hasFromTo()) {
        if (getFromTo()
            != other.getFromTo()) return false;
      }
      if (hasSendTo() != other.hasSendTo()) return false;
      if (hasSendTo()) {
        if (getSendTo()
            != other.getSendTo()) return false;
      }
      if (hasContent() != other.hasContent()) return false;
      if (hasContent()) {
        if (!getContent()
            .equals(other.getContent())) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (getType()
            != other.getType()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFromTo()) {
        hash = (37 * hash) + FROMTO_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFromTo());
      }
      if (hasSendTo()) {
        hash = (37 * hash) + SENDTO_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSendTo());
      }
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessageProtocol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageProtocol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MessageProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessageProtocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.MessageProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.MessageProtocol)
        MessageProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageProto.internal_static_protocol_MessageProtocol_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageProto.internal_static_protocol_MessageProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageProtocol.class, Builder.class);
      }

      // Construct using com.regent.rpush.dto.protocol.MessageProto.MessageProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        fromTo_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        sendTo_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageProto.internal_static_protocol_MessageProtocol_descriptor;
      }

      @Override
      public MessageProtocol getDefaultInstanceForType() {
        return MessageProtocol.getDefaultInstance();
      }

      @Override
      public MessageProtocol build() {
        MessageProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MessageProtocol buildPartial() {
        MessageProtocol result = new MessageProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fromTo_ = fromTo_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sendTo_ = sendTo_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageProtocol) {
          return mergeFrom((MessageProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessageProtocol other) {
        if (other == MessageProtocol.getDefaultInstance()) return this;
        if (other.hasFromTo()) {
          setFromTo(other.getFromTo());
        }
        if (other.hasSendTo()) {
          setSendTo(other.getSendTo());
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000004;
          content_ = other.content_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasFromTo()) {
          return false;
        }
        if (!hasSendTo()) {
          return false;
        }
        if (!hasContent()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessageProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessageProtocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long fromTo_ ;
      /**
       * <code>required int64 fromTo = 2;</code>
       * @return Whether the fromTo field is set.
       */
      @Override
      public boolean hasFromTo() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int64 fromTo = 2;</code>
       * @return The fromTo.
       */
      @Override
      public long getFromTo() {
        return fromTo_;
      }
      /**
       * <code>required int64 fromTo = 2;</code>
       * @param value The fromTo to set.
       * @return This builder for chaining.
       */
      public Builder setFromTo(long value) {
        bitField0_ |= 0x00000001;
        fromTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 fromTo = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromTo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fromTo_ = 0L;
        onChanged();
        return this;
      }

      private long sendTo_ ;
      /**
       * <code>required int64 sendTo = 4;</code>
       * @return Whether the sendTo field is set.
       */
      @Override
      public boolean hasSendTo() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int64 sendTo = 4;</code>
       * @return The sendTo.
       */
      @Override
      public long getSendTo() {
        return sendTo_;
      }
      /**
       * <code>required int64 sendTo = 4;</code>
       * @param value The sendTo to set.
       * @return This builder for chaining.
       */
      public Builder setSendTo(long value) {
        bitField0_ |= 0x00000002;
        sendTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 sendTo = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendTo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sendTo_ = 0L;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>required string content = 1;</code>
       * @return Whether the content field is set.
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string content = 1;</code>
       * @return The content.
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string content = 1;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string content = 1;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 1;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>required int32 type = 3;</code>
       * @return Whether the type field is set.
       */
      @Override
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required int32 type = 3;</code>
       * @return The type.
       */
      @Override
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.MessageProtocol)
    }

    // @@protoc_insertion_point(class_scope:protocol.MessageProtocol)
    private static final MessageProtocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessageProtocol();
    }

    public static MessageProtocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<MessageProtocol>
        PARSER = new com.google.protobuf.AbstractParser<MessageProtocol>() {
      @Override
      public MessageProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageProtocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageProtocol> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MessageProtocol> getParserForType() {
      return PARSER;
    }

    @Override
    public MessageProtocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_MessageProtocol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_MessageProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\033protocol/MessageProto.proto\022\010protocol\"" +
      "P\n\017MessageProtocol\022\016\n\006fromTo\030\002 \002(\003\022\016\n\006se" +
      "ndTo\030\004 \002(\003\022\017\n\007content\030\001 \002(\t\022\014\n\004type\030\003 \002(" +
      "\005B-\n\035com.regent.rpush.dto.protocolB\014Mess" +
      "ageProto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_MessageProtocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_MessageProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_MessageProtocol_descriptor,
        new String[] { "FromTo", "SendTo", "Content", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
