server:
  port: 8122
spring:
  application:
    name: rpush-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka-service-ip:localhost}:${eureka-sevice-port:8761}/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"

rpush:
  ip: ${rpush-ip:none}
  server:
    port: 1111
    heartBeatTime: 20 # 20秒没有心跳就关闭对应客户端连接
  web-socket:
    port: 9092
